import type { Metadata } from "next";
import { DM_Sans } from "next/font/google";
import localFont from "next/font/local";
import "./globals.css";

// Google font
const dmSans = DM_Sans({
  variable: "--font-dm-sans",
  subsets: ["latin"],
});

// Local Geist Sans
const geistSans = localFont({
  src: "./fonts/GeistVF.woff", // adjust path as needed
  variable: "--font-geist-sans",
  weight: "100 900",
});

// Local Geist Mono
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff", // adjust path as needed
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${dmSans.variable} ${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
